# Generated by Django 5.2.15 on 2026-08-15 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_notification_related_application_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='interview_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='interview_link',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='interview_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='interview_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
