# Generated by Django 5.2.15 on 2026-08-17 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_jobapplication_interview_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='company_type',
            field=models.CharField(choices=[('MNC', 'MNC'), ('STARTUP', 'Startup'), ('NEW_STARTUP', 'New Startup'), ('ENTERPRISE', 'Enterprise')], default='MNC', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('NEW_JOB', 'New Job Posted'), ('SKILLS_MATCH', 'Skills Match'), ('HIGH_MATCH', 'High Match'), ('LOW_COMPETITION', 'Low Competition'), ('APPLICATION_SUBMITTED', 'Application Submitted'), ('SHORTLISTED', 'Shortlisted'), ('INTERVIEW_SCHEDULED', 'Interview Scheduled'), ('REJECTED', 'Rejected'), ('SELECTED', 'Selected'), ('NEW_RECOMMENDATION', 'New Recommendation'), ('NEW_APPLICANT', 'New Applicant'), ('STATUS_UPDATED', 'Status Updated'), ('SYSTEM', 'System Notification'), ('STARTUP_HIRING', 'Startup Hiring Alert'), ('APPLICATION_STATUS', 'Application Status Alert'), ('GENERAL', 'General Notification')], default='SYSTEM', max_length=50),
        ),
    ]
