# Generated by Django 5.2.15 on 2026-07-08 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('JOB_SEEKER', 'Job Seeker'), ('RECRUITER', 'Recruiter'), ('EMPLOYER', 'Employer'), ('ADMIN', 'Admin')], default='JOB_SEEKER', max_length=20),
        ),
    ]
