# Generated by Django 5.2.15 on 2026-07-30 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_cgpa_user_college_user_company_size_user_degree_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='extracted_skills',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_job_type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_location',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='resume_summary',
            field=models.TextField(blank=True, default=''),
        ),
    ]
