# Generated by Django 5.2.15 on 2026-08-29 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_certificates_user_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='resume_gaps',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='resume_improvements',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='resume_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='resume_strengths',
            field=models.TextField(blank=True, default=''),
        ),
    ]
